name: "Install Dependencies"
description: "Install dependencies, fetching from cache when possible"
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.12.0

    - name: Install Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "pnpm"

    - name: Install NPM Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
