name = "helios"
compatibility_date = "2022-06-24"
workers_dev = false
minify = true
node_compat = true

# [build]
# command = "npm install && npm run build"


# The below is used if you used miniflare directly but with wrangler 2 integrating miniflare there isn't much of a need for it.
[dev]
ip = "127.0.0.1"
