name = "olympus-v3"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-09-06"

[site]
bucket = "./public"


[[ kv_namespaces ]]
  binding = "HELIOS"
  id = "ebe5f7523c3e4b3cb24d0d09e943b561"
  preview_id = "e5f7fce4e4b7496b8f2fb4745ccf943d"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "olympus"
database_id = "75eee409-72e2-4df4-a6bb-e790aff52cbd "

#[build]
#command = "npm run build"
