d1_databases = [
  { binding = "DB", database_name = "olympus", database_id = "<UUID>", preview_database_id = "DB", migrations_dir = "./migrations" }
]

kv_namespaces = [
  { binding = "KV", id = "<UUID>", preview_id = "KV" }
]
