import './globals.css';
import { ThemeProvider } from 'next-themes';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import tailwindConfig from '../../tailwind.config';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={inter.className}>
        <ThemeProvider
          enableColorScheme={true}
          defaultTheme={'dark'}
          themes={tailwindConfig.daisyui.themes}
          disableTransitionOnChange={true}
          storageKey={'olympus-theme'}
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
