name = "janus"
main = "src/index.ts"
compatibility_date = "2022-07-23"
workers_dev = false
minify = true
node_compat = true

kv_namespaces = [
    { binding = "HELIOS_KV", id = "ebe5f7523c3e4b3cb24d0d09e943b561", preview_id = "e5f7fce4e4b7496b8f2fb4745ccf943d" }
]

r2_buckets = [
    { binding = "HELIOS_R2", bucket_name = "helios-r2", preview_bucket_name = "helios-pvw-r2" }
]

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "olympus"
database_id = "75eee409-72e2-4df4-a6bb-e790aff52cbd"
preview_database_id = "75eee409-72e2-4df4-a6bb-e790aff52cbd"

# [build]
# command = "npm install && npm run build"
