WEATHERAPI_KEY="{{ op://Private/5yfpacpx76vsorecmkdby2mdlq/api_key }}"
AUTH_SECRET="{{ op://Private/njuvxrshvgijxbpybbx2vhq7qu/session_secret }}"
AUTH_AUTH0_CALLBACK_URL="http://localhost:8788/auth/auth0/callback"
AUTH_AUTH0_ID="{{ op://Private/njuvxrshvgijxbpybbx2vhq7qu/auth0_client_id }}"
AUTH_AUTH0_SECRET="{{ op://Private/njuvxrshvgijxbpybbx2vhq7qu/auth0_client_secret }}"
AUTH_AUTH0_DOMAIN="https://{{ op://Private/njuvxrshvgijxbpybbx2vhq7qu/auth0_domain }}"
