name = "helios"
main = "src/index.ts"
compatibility_date = "2022-09-14"
workers_dev = false
minify = true
node_compat = true

[[kv_namespaces]]
  binding = "KV"
  id = "ebe5f7523c3e4b3cb24d0d09e943b561"
  preview_id = "e5f7fce4e4b7496b8f2fb4745ccf943d"

[[r2_buckets]]
  binding = "R2"
  bucket_name = "helios-r2"
  preview_bucket_name = "helios-pvw-r2"

[[d1_databases]]
  binding = "DB"
  database_id = "75eee409-72e2-4df4-a6bb-e790aff52cbd"
  preview_id = "75eee409-72e2-4df4-a6bb-e790aff52cbd"

[build]
command = "pnpm build:esbuild"

[dev]
port = 8789
inspector_port = 9230
