name = "helios"
main = "src/index.ts"
compatibility_date = "2022-09-14"
workers_dev = false
minify = true
node_compat = true

[[kv_namespaces]]
  binding = "HELIOS_KV"
  id = "ebe5f7523c3e4b3cb24d0d09e943b561"
  preview_id = "e5f7fce4e4b7496b8f2fb4745ccf943d"

[[r2_buckets]]
  binding = "HELIOS_R2"
  bucket_name = "helios-r2"
  preview_bucket_name = "helios-pvw-r2"

[build]
command = "pnpm build"

[dev]
port = 8789
