name = "olympus-helios"

workers_dev = false
main = "./server.ts"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-09-06"

[site]
bucket = "./public"


[[ kv_namespaces ]]
  binding = "KV"
  id = "ebe5f7523c3e4b3cb24d0d09e943b561"
  preview_id = "e5f7fce4e4b7496b8f2fb4745ccf943d"

#[build]
#command = "npm run build"
