name: "1Password environment"
description: "Load 1password environment variables for subsequent access"
runs:
  using: "composite"
  steps:
    - name: Configure 1Password Service Account
      uses: 1password/load-secrets-action/configure@v1
      with:
        service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    - name: Load envrionment variables
      id: load-1password-env
      uses: 1password/load-secrets-action@v1
      with:
        export-env: false
      env:
        GH_ACCESS_TOKEN: op://Dev/3hwptanyvn7stnz63n5urtdwo4/personal_access_token
        NPM_PUBLISH_TOKEN: op://Dev/gpwxrxcaff6ksvee6bgbmbqpca/publish_root_token
