name: Release
on:
  push:
    branches:
      - main
    paths:
      - 'packages/cfsetup/**'
      - '.github/workflows/cfsetup.yml'

defaults:
  run:
    shell: bash

env:
  CI: true
  HUSKY: 0
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  release:
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    if: ${{ github.repository_owner == 'nwlnexus' }}
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
        with:
          # See https://github.com/changesets/action/issues/187
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.12.0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      #      - name: Lint code
      #        run: |
      #          pnpm lint
      #          pnpm test

      - name: Build app
        run: pnpm run build

      - name: Check for other errors
        run: pnpm run check
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"

      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          version: node .github/changeset-version.js
          publish: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          NODE_ENV: "production"
