name: Deploy all pages sites
on:
  push:
    branches:
      - main
  pull_request:
      types: [synchronize, opened, reopened, labeled, unlabeled]

defaults:
  run:
    shell: bash

env:
  CI: true
  HUSKY: 0
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  helios:
    name: Helios
    if: github.repository_owner == 'nwlnexus' && (github.event_name != 'pull_request' || (github.event_name == 'pull_request' && contains(github.event.*.labels.*.name, 'preview:helios' )))
    uses: ./.github/workflows/deploy-pages-project.yml
    with:
      package: "@nwlnexus/helios"
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
