name:  Deploy Pages Project

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
    secrets:
      CLOUDFLARE_ACCOUNT_ID:
        required: true
      CLOUDFLARE_API_TOKEN:
        required: true

jobs:
  publish:
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.package }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: pnpm run build
        env:
          CI_OS: ${{ runner.os }}

      - name: Deploy to Pages
        run: pnpm --filter ${{ inputs.package }} run deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets. CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
