name: 'Deploy Docs'
on:
  push:
    paths:
      - 'apps/docs/**'
      - '.github/workflows/docs.yml'

defaults:
  run:
    shell: bash
    working-directory: apps/docs

env:
  CI: true
  HUSKY: 0
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  docs-git-tasks:
    name: 'Docs: Setup Git, Node and dependencies'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build Hugo
        run: pnpm build

      - name: Deploy Docs Pages App
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${[ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: nwlnexus-docs
          directory: apps/docs/public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
