name: 'Deploy Docs'
on:
  push:
    paths:
      - 'apps/docs/**'
      - '.github/workflows/docs.yml'

defaults:
  run:
    shell: bash
    working-directory: apps/docs

env:
  CI: true
  HUSKY: 0
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  docs-git-tasks:
    name: 'Docs: Setup Git, Node and dependencies'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --forzen-lockfile

      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build Hugo
        run: pnpm build

      - name: Deploy Docs Pages App Production
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'apps/docs'
          command: pages publish --project-name='nwlnexus-docs' --branch=$BRANCH_NAME ./public
          secrets: |
            SESSION_TAG
            SESSION_SECRETS
            AUTH0_CALLBACK_URL
            AUTH0_CLIENT_ID
            AUTH0_CLIENT_SECRET
            AUTH0_DOMAIN
            APP_BASE_URL
            METRONOME_API_KEY
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          SESSION_TAG: ${{ secrets.SESSION_TAG }}
          SESSION_SECRETS: ${{ secrets.SESSION_SECRETS }}
          AUTH0_CALLBACK_URL: ${{ secrets.AUTH0_CALLBACK_URL }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
          METRONOME_API_KEY: ${{ secrets.METRONOME_API_KEY }}
