name: Add issues to DevProd project

on:
  issues:
    types: [opened, labeled, unlabeled, transferred]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/nwlnexus/projects/1
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          labeled: bug, enhancement
          label-operator: OR
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/nwlnexus/projects/6
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          labeled: cfsetup
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/nwlnexus/projects/3
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          labeled: hermes
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/nwlnexus/projects/5
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          labeled: helios
