name: Package Prerelease

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'packages/**/*'
      - '.github/workflows/prereleases.yml'

jobs:
  prerelease:
    strategy:
      matrix:
        packages: ["@nwlnexus/cfsetup"]
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    if: ${{ github.repository_owner == 'nwlnexus' }}
    name: Build & Publish a beta release to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Load envrionment variables
        id: load-1password-env
        uses: 1password/load-secrets-action@v1
        with:
          export-env: false
        env:
          GH_ACCESS_TOKEN: op://h2apd5x5ncu6djh6svr3lcr25a/3hwptanyvn7stnz63n5urtdwo4/gh_pat_classic
          NPM_PUBLISH_TOKEN: op://h2apd5x5ncu6djh6svr3lcr25a/gpwxrxcaff6ksvee6bgbmbqpca/publish_root_token
          COMPAT_DATE: op://h2apd5x5ncu6djh6svr3lcr25a/nztlf5np6ljbte7yhwi4xfsqjm/compat_date
          WEATHERAPI_KEY: op://h2apd5x5ncu6djh6svr3lcr25a/fsdgtvziuoqdeq36rqkhbwzcde/api_key
          AUTH_SECRET: op://h2apd5x5ncu6djh6svr3lcr25a/nztlf5np6ljbte7yhwi4xfsqjm/session_secret
          AUTH_AUTH0_ID: op://h2apd5x5ncu6djh6svr3lcr25a/nztlf5np6ljbte7yhwi4xfsqjm/auth0_client_id
          AUTH_AUTH0_SECRET: op://h2apd5x5ncu6djh6svr3lcr25a/nztlf5np6ljbte7yhwi4xfsqjm/auth0_client_secret
          AUTH_AUTH0_DOMAIN: op://h2apd5x5ncu6djh6svr3lcr25a/nztlf5np6ljbte7yhwi4xfsqjm/auth0_domain

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Modify package.json version
        run: node .github/version-script.js ${{ matrix.packages }}

      - name: Prettify code base
        run: pnpm run prettify
        env:
          NODE_ENV: "production"
          CI_OS: ${{ runner.os }}

      - name: Build
        run: pnpm --filter=${{ matrix.packages }} run build
        env:
          NODE_ENV: "production"
          CI_OS: ${{ runner.os }}

      - name: Check for errors
        run: pnpm --filter=${{ matrix.packages }} run check
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"

      - name: Publish Beta to NPM
        run: pnpm --filter=${{ matrix.packages }} publish --tag beta
        env:
          NPM_PUBLISH_TOKEN: ${{ steps.load-1password-env.outputs.NPM_PUBLISH_TOKEN }}

      - name: Get Package Version
        run: echo "CFSETUP_VERSION=$(npm view ${{ matrix.packages }}@beta version)" >> $GITHUB_ENV
