name: Prerelease

on:
  push:
    branches:
      - main
jobs:
  prerelease:
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    if: ${{ github.repository_owner == 'nwlnexus' }}
    name: Build & Publish a beta release to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Load 1password envrionment
        uses: ./.github/actions/1password-env

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

#      - name: "Create .env file"
#        run: |
#          touch .env
#          echo TURBO_API=${{ secrets.TURBO_API }} >> .env
#          echo TURBO_TEAM=${{ secrets.TURBO_TEAM }} >> .env
#          echo TURBO_TOKEN=${{ secrets.TURBO_TOKEN }} >> .env
#          echo TURBO_REMOTE_CACHE_SIGNATURE_KEY=${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }} >> .env

      - name: Modify package.json version
        run: node .github/version-script.js

      - name: Build
        run: pnpm run build
        env:
          NODE_ENV: "production"
          CI_OS: ${{ runner.os }}

      - name: Check for errors
        run: pnpm run check
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"

      - name: Publish Beta to NPM
        run: pnpm publish --tag beta
        env:
          NPM_PUBLISH_TOKEN: ${{ steps.load-1password-env.outputs.NPM_PUBLISH_TOKEN }}
        working-directory: packages/cfsetup

      - name: Get Package Version
        run: echo "CFSETUP_VERSION=$(npm view @nwlnexus/cfsetup@beta version)" >> $GITHUB_ENV
        working-directory: packages/cfsetup
