name: 'PROD: Deploy Helios'
on:
  push:
    branches:
      - main
    paths:
      - 'apps/helios/**'
      - '.github/workflows/prod-deploy-helios.yml'

defaults:
  run:
    shell: bash
    working-directory: apps/helios

env:
  CI: true
  HUSKY: 0
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  helios_build-and-deploy:
    name: 'Helios: Build and deploy to CF'
    runs-on: ubuntu-latest
    steps:
      - uses: nwlnexus/olmypus-net/.github/workflows/git-tasks.yml@main
        with:
          secrets: inherit

      - name: Install dependencies
        run: pnpm install

#      - name: Run Unit Tests
#        run: pnpm test

      - name: Build app
        run: pnpm build

      - name: Deploy Helios
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'apps/helios'
          precommads: |
            pnpm dlx wrangler@d1 d1 execute olympus --file=../../schema.sql
          secrets: |
            SESSION_TAG
            SESSION_SECRETS
            AUTH0_CALLBACK_URL
            AUTH0_CLIENT_ID
            AUTH0_CLIENT_SECRET
            AUTH0_DOMAIN
            APP_BASE_URL
            METRONOME_API_KEY
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          SESSION_TAG: ${{ secrets.SESSION_TAG }}
          SESSION_SECRETS: ${{ secrets.SESSION_SECRETS }}
          AUTH0_CALLBACK_URL: ${{ secrets.AUTH0_CALLBACK_URL }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
          METRONOME_API_KEY: ${{ secrets.METRONOME_API_KEY }}
