name: 'PROD: Deploy Remix App'
on:
  push:
    branches:
      - main
    paths:
      - 'apps/remix-app/**'
      - '.github/workflows/prod-deploy-remix-app.yml'

defaults:
  run:
    shell: bash
    working-directory: apps/remix-app

env:
  CI: true
  HUSKY: 0
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  remix-build-and-deploy:
    name: 'Remix App: Build and deploy to CF'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('../../pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm lint

      - name: Run Unit Tests
        run: pnpm test

      - name: Build app
        run: pnpm build

      - name: Deploy Remix App
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'apps/remix-app'
          secrets: |
            SESSION_TAG
            SESSION_SECRETS
            AUTH0_CALLBACK_URL
            AUTH0_CLIENT_ID
            AUTH0_CLIENT_SECRET
            AUTH0_DOMAIN
            APP_BASE_URL
            METRONOME_API_KEY
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          SESSION_TAG: ${{ secrets.SESSION_TAG }}
          SESSION_SECRETS: ${{ secrets.SESSION_SECRETS }}
          AUTH0_CALLBACK_URL: ${{ secrets.AUTH0_CALLBACK_URL }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
          METRONOME_API_KEY: ${{ secrets.METRONOME_API_KEY }}
