name: Release
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  CI: true
  HUSKY: 0
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  release:
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    if: ${{ github.repository_owner == 'nwlnexus' }}
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Load 1password envrionment
        uses: ./.github/actions/1password-env

      - uses: actions/checkout@v4
        with:
          # See https://github.com/changesets/action/issues/187
          token: ${{ steps.load-1password-env.outputs.GH_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build app
        run: pnpm run build

      - name: Check for other errors
        run: pnpm run check
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"

      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          version: node .github/version-script.js
          publish: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ steps.load-1password-env.outputs.GH_ACCESS_TOKEN }}
          NPM_PUBLISH_TOKEN: ${{ steps.load-1password-env.outputs.NPM_PUBLISH_TOKEN }}
          NODE_ENV: "production"
