name: Release
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  CI: true
  HUSKY: 0
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  release:
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    if: ${{ github.repository_owner == 'nwlnexus' }}
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      deployments: write
    steps:
      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Load envrionment variables
        id: load-1password-env
        uses: 1password/load-secrets-action@v1
        with:
          export-env: false
        env:
          GH_ACCESS_TOKEN: op://h2apd5x5ncu6djh6svr3lcr25a/3hwptanyvn7stnz63n5urtdwo4/gh_pat_classic
          NPM_PUBLISH_TOKEN: op://h2apd5x5ncu6djh6svr3lcr25a/gpwxrxcaff6ksvee6bgbmbqpca/publish_root_token
          COMPAT_DATE: op://h2apd5x5ncu6djh6svr3lcr25a/nztlf5np6ljbte7yhwi4xfsqjm/compat_date
          WEATHERAPI_KEY: op://h2apd5x5ncu6djh6svr3lcr25a/fsdgtvziuoqdeq36rqkhbwzcde/api_key
          AUTH_SECRET: op://h2apd5x5ncu6djh6svr3lcr25a/nztlf5np6ljbte7yhwi4xfsqjm/session_secret
          AUTH_AUTH0_ID: op://h2apd5x5ncu6djh6svr3lcr25a/nztlf5np6ljbte7yhwi4xfsqjm/auth0_client_id
          AUTH_AUTH0_SECRET: op://h2apd5x5ncu6djh6svr3lcr25a/nztlf5np6ljbte7yhwi4xfsqjm/auth0_client_secret
          AUTH_AUTH0_DOMAIN: op://h2apd5x5ncu6djh6svr3lcr25a/nztlf5np6ljbte7yhwi4xfsqjm/auth0_domain

      - uses: actions/checkout@v4
        with:
          # See https://github.com/changesets/action/issues/187
          token: ${{ steps.load-1password-env.outputs.GH_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build app
        run: pnpm run build

      - name: Check for other errors
        run: pnpm run check
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"

      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          version: node .github/version-script.js
          publish: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ steps.load-1password-env.outputs.GH_ACCESS_TOKEN }}
          NPM_PUBLISH_TOKEN: ${{ steps.load-1password-env.outputs.NPM_PUBLISH_TOKEN }}
          NODE_ENV: "production"
